stages:
  - deploy
  - deploy-documentation

Deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY

Documentation:
  image: node:16
  stage: deploy-documentation
  before_script:
    - npm install -g rdme
  script:
    - rdme openapi <(curl 'https://furaffinity-api.herokuapp.com/openapi.json') --key=$READMEIO_API_KEY --id=$READMEIO_APP_ID --version=$(git describe --tags)
