before_script:
  - python --version

stages:
  - Static Analysis
  - Deploy

mypy:
  stage: Static Analysis
  image: python:3.10
  before_script:
    - python -m pip install mypy types-beautifulsoup4
  script:
    - python -m mypy --install-types --non-interactive --ignore-missing-imports --follow-imports=skip --strict-optional app

flake8:
  stage: Static Analysis
  image: python:3.10
  before_script:
    - python -m pip install flake8
  script:
    - python -m flake8 --max-line-length=120 --exclude app/description.py app

Deployment:
  stage: Deploy
  image: ruby:3.1
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
