stages:
  - deploy

Deployment:
  stage: deploy
  script:
    - git push --follow-tags https://$(echo -n $HEROKU_USERNAME | sed -e "s/@/%40/g"):$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git HEAD:main
