name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.13.5

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Style Test
        id: test
        run: |
          python -m pip install flake8
          python -m flake8 --max-line-length=120 --exclude app/description.py app

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Types test
        id: test
        run: |
          python -m pip install mypy types-beautifulsoup4
          python -m mypy --install-types --non-interactive --ignore-missing-imports --follow-imports=skip --strict-optional app
